version: "3"
services:

  client:
    image: "grszyman/complex-client"
    mem_limit: 128m
    hostname: client

  api:
    image: "grszyman/complex-api"
    mem_limit: 128m
    hostname: api
    environment:
      - REDIS_HOST=$REDIS_HOST
      - REDIS_PORT=$REDIS_PORT
      - PG_HOST=$PG_HOST
      - PG_PORT=$PG_PORT
      - PG_DATABASE=$PG_DATABASE
      - PG_USER=$PG_USER
      - PG_PASSWORD=$PG_PASSWORD
      -
  worker:
    image: "grszyman/complex-worker"
    mem_limit: 128m
    hostname: worker
    environment:
      - REDIS_HOST=$REDIS_HOST
      - REDIS_PORT=$REDIS_PORT
      -
  nginx:
    image: "grszyman/complex-nginx"
    mem_limit: 128m
    hostname: nginx
    ports:
      - "80:80"
