version: '3'
services:

  postgres:
    image: 'postgres:latest'
    environment:
      POSTGRES_PASSWORD: postgres_password

  redis:
    image: 'redis:latest'

  nginx:
    build:
      context: ./nginx
      dockerfile: Dockerfile.dev
    depends_on:
      - api
      - client
    restart: always
    ports:
      - '3050:80'

  api:
    build:
      context: ./api
      dockerfile: Dockerfile.dev
    depends_on:
      - redis
      - postgres
    volumes:
      - /app/node_modules
      - ./api:/app
    environment:
      - REDIS_HOST=redis
      - REDIS_POST=6379
      - PG_HOST=postgres
      - PG_PORT=5432
      - PG_DATABASE=postgres
      - PG_USER=postgres
      - PG_PASSWORD=postgres_password

  client:
    build:
      context: ./client
      dockerfile: Dockerfile.dev
    depends_on:
      - api
    volumes:
      - /app/node_modules
      - ./client:/app
    environment:
      - WDS_SOCKET_PORT=0

  worker:
    build:
      context: ./worker
      dockerfile: Dockerfile.dev
    depends_on:
      - redis
    volumes:
      - /app/node_modules
      - ./worker:/app
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379
