version: "3"
services:

  client:
    image: "grszyman/complex-client"
    mem_limit: 128m
    hostname: client

  api:
    image: "grszyman/complex-api"
    mem_limit: 128m
    hostname: api
    env_file:
    - .env

  worker:
    image: "grszyman/complex-worker"
    mem_limit: 128m
    hostname: worker
    env_file:
      - .env

  nginx:
    image: "grszyman/complex-nginx"
    mem_limit: 128m
    hostname: nginx
    ports:
      - "80:80"
