name: Pipeline
on: push

jobs:
  setup:
    runs-on: ubuntu-latest
    steps:
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_TOKEN }}

  test:
    runs-on: ubuntu-latest
    needs: setup
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Build tests
        run: docker build -t grszyman/docker-client-dev -f ./client/Dockerfile.dev ./client

      - name: Run tests
        run: docker run -e CI=true grszyman/docker-client-dev npm test

  publish:
    runs-on: ubuntu-latest
    needs: test
    if: github.ref == 'refs/heads/main'
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Build client
        run: docker build -t grszyman/complex-client ./client

      - name: Build nginx
        run: docker build -t grszyman/complex-nginx ./nginx

      - name: Build api
        run: docker build -t grszyman/complex-api ./api

      - name: Build worker
        run: docker build -t grszyman/complex-worker ./worker

#  deploy:
#    runs-on: ubuntu-latest
#    needs: test
#    if: github.ref == 'refs/heads/main'
#    steps:
#      - name: Checkout repository
#        uses: actions/checkout@v2
#
#      - name: Build production
#        run: docker build -t grszyman/docker-react-2022:v${{ github.sha }} -t grszyman/docker-react-2022:latest .
#
#      - name: Generate deployment package
#        run: zip -r deploy.zip . -x '*.git*'
#
#      - name: Deploy to EB
#        uses: einaregilsson/beanstalk-deploy@v18
#        with:
#          aws_access_key: ${{ secrets.AWS_ACCESS_KEY }}
#          aws_secret_key: ${{ secrets.AWS_SECRET_KEY }}
#          application_name: docker-react-2022
#          environment_name: Dockerreact2022-env
#          existing_bucket_name: elasticbeanstalk-us-east-2-840579016403
#          region: us-east-2
#          version_label: ${{ github.sha }}
#          deployment_package: deploy.zip